services:
    # backend:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - "5000:5000"
    #     env_file:
    #         - .env
    #     depends_on:
    #         - database

    database:
        image: postgres:latest
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    pgdata: